apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookorders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingorder
  template:
    metadata:
      labels:
        app: bookcrossingorder
    spec:
      hostNetwork: true
      containers:
        - image: bookorder:0.0.1-SNAPSHOT
          name: bookorders
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
              name: bookorders