apiVersion: apps/v1
kind: Deployment
metadata:
  name: boxes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcrossingbox
  template:
    metadata:
      labels:
        app: bookcrossingbox
    spec:
      hostNetwork: true
      containers:
        - image: box:0.0.1-SNAPSHOT
          name: boxes
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
              name: boxes